server {
    listen 80;
    server_name localhost;

    client_max_body_size 50M;

    # Se você quiser redirecionar 80 para 443 futuramente:
    # return 301 https://$host$request_uri;

    location / {
        proxy_pass http://hc-jornada-t3:10000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Configuração SSL comentada caso queira ativar no futuro:
# server {
#     listen 443 ssl;
#     server_name localhost;
#     ssl_certificate /etc/nginx/certs/hc-jornada-t3.crt;
#     ssl_certificate_key /etc/nginx/certs/hc-jornada-t3.key;
#     client_max_body_size 50M;
#     location / {
#         proxy_pass http://hc-jornada-t3:10000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }
